language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: Znmv/xgV/JvxVQC2zDFvi93oUEt4mr7RDGHc8t8IsVi6CWyQDNoIhDxaJF7bES1ZU7uNCwT5SNcCeO0MH0oXPzAnIRT8UJY+w6nByDTFqhdmWfhy0anYC7LYrMjrjiK0MVbF8cHk56PWya/HxF1hbqcPjRgX45Myx1HNyJMlSaO3uiaYLFKzQTmfm3KSY5r2CqdwTFDSb9dYJpFpkDXr5/QC6iBYQ707A3f53r559YEVd/LsCnNqvSgGfNRGabZW7vBx5vnYCYhdfWlE6s8ddfyWaAu4548wi52ieF30/xZ3yrTlsRkQJfG082067bcyVvIEmVzC2ta2pd06RRvpHgVWDn+jMft73MtR31MgttpYMtld6/ixHzuI97YC+X/ADlcy9Nfz1Rg6G3zCt5/5Z/Jx56Yb2gdzA/eyBC61735Pot4hCoBQRBfoyON6XmW8jTA/Zw82kJEJrvqAJoBEfxBiY4jSkkWqWLUW3VanhkloZEXh4FAwaaj+bCJX6DWMTPaqTFvwp7IGUx2YnTQt9Vamn+VY6CxhCNs60RP9tOLPnPbPsAgPhoUIocnz066IGkvcLkL/prf48dzZL/aLRxvTW29W5iClT/0eFxLSgTdW1mna7UxyE6gNhoNZRUekclLSfZY+ksLmZLU0t72zL41LT0M0JeGy5Op1v/LSGw4=
  - secure: tAh6zjMjXWcWlVx3VOOE7vIn9h79iGZwI4ywSWRBFc9TJ25PIqFi59jAbOuPYQWtGN/9Q8JKA7pTUjqT4zZIXPEozYuEctCWHEiPoKztRtsvUMw6ZHa2g5XMQo1ysCjOYg36CwGk0i7ta3y34SwnaS6+cgX+pI/p7/2hWBpCYmdSAB6bC+8sh+4xC2E3RK43j1NFXYl11JNUgvtGFOkdgUIRCvGwxVb7209uQcVX/a3p8u5Sk4/lC2vAD4jwHGB9JAuFkvha9WH7XD4sAF2LseBVST3fyEbAP/nxCbfPPAkXhYvLA8dOlIq98nxmgeofq77Iev7ovfoxRMHD/PKw0glDkvDJsNYssIq+EB/r6aHZpqnfAmueGNs2DwAZFYKa+tu1Xv2Y0Ezv46Gjhx1O7a+OLbYuHqlmjRtQ00s5Z+r8C9C2H/5OWZlMr9sDWsFAzsoOaSBD9v2eYyiuNjlmasfJcKP7nn5zkTh+G/5J6j+GzGdvcynFkzffsqolRoNUljTkms4fJxcxBC/Y5yb+deJQL7oieiaIoMn3DNhaHzFgPZgQsONbDxxpNWrWsJySJMPxe/8LbIrY00vROiFXx6Gv0RAwXlHPuKs55sWrMBeculf0wKHaih3LHz/O8PXQvq868nMKbScdv8w0JL3yZ8KcgQTQwHY+GiRarL9Eo1E=
