language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: HWwtTkU9A+BuOOOoTeDiE9JmvtR+5S9LdcpJh+rmwIiQiBIONiLujU4J7dAhAOxkJeZSzb6x9oVuWe1E5QDTE29aEiKedGbxJXMjJi30KXwBJSOY/FSHx+A7lXrgfpAjFzNsrsRawtja4I+5AqGlP+N+UUjVucxjwlHnptAZ+v8TmS1qP6Id6dYUR9VzJvGa3Z2/MLE0CZBwfFUoojZ/Sf2oWMlDL8gwBirISKG2uG45I1cQ3PlT9ib2zKg+B/7Ax7ONKlUirIM5Sbml9j2UAOvnrBPy3O9/4LA2DB5xVnLvl1XeJ5Lc2ql00XzAwcVdF0+9vdzT03aOdXdXY5jacxvvFgQJMykySIMejbO2MQl9PY+feCo8iMhwK/521RrumqidNf+OvS5rvoFPBKYCiPSFmFkZQaAH/y8/Ty8CovQsLyqm2fxyYjDUXEyN3u6nDAAMv/PMoqDAY6BUUQbuByzpyLOq5hlFQbhYIkicBak3QD1c5BYLdhRXJXR5SjXTHr/whDMmpWi37+5mw0U1H8X8XBpxvnR9/1pv58lGyGRosvk5Kxsww4wBmr7deZHy1y3a78wFjw9FA2gLWSWQgsooORoRhm4UNMqJbpIzwoMrsRIhPuAONlgEzaxJsbLLSGuGUeZUHUbVTeLyTEUqO3VqB45/TLz1FJcTSH3ghNA=
  - secure: sFGpWEABdH6CAXg+0dZaEOk72gwlBiO2QTF1VAJ+lVVgtWHEE9OfBYeVLUmldJVFyB44ajkTuMnaJHyT2eyuUaZEsOmgQ9dF4FvWkaVKAuyEoufAG6x/1jP6Kgin5SklCmyqN3lA72zw3jbDBFGYWFGnxTXsBiX9tR6pNh2TtV3rAQtWoqmgmK+d+YJb7ZnokRV/fAHdCwQ+Ne1TfAZN/QbhHhmz5eQssKZR33Ccps3K5yE7Izf/OmuadGdqSb5Dfw9Phr7Uo5aKit2SIjv+UsKpKgStuDxvxos6XusDVaOQofWyliudBr+EFfg8b9xruLkA5Oa0wHnz3I7Eyltx2M/ne7hjyw+ASAmx1kWI8+JPXh8BGVk+gUZwz9fwrAeGSmYFW5Dnx3AHDQK+dqKUQsHIb+lnzQTiVKs+XVoL5Y9VaUit56cwdw3wwl8b8qQDNfUoU07Vg+RB1Otm+BMva0CvJ0t+MQ9NncpW45N8QjuuQx8GZvm24gYNUZSBS8NWRgMSo/Qwp0ayWqq5QZrOwayIQAMqzXZjhH9BIzIA/rg+la5w/nIQmSeNkurcIoTMkEOkkqNN+GUin3I9llMUpZ39dXppvru1IrL7kUyVt/dNzvm9BGHNmGeVvvnnedQ2cfkZtfGma5afXBrb2uH9+EivTjp9PiVrqkwVY7/Ggng=
