language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: D96k/zaPKM2gJ0i4ibnW8Ksg/qHFcORelZeGeZEKIvwmrXSm3lEMnxSuVS8MHL+qLWUzDZfoDy8OIzdU/ufpDVdkGKJpl9c3jTLL4+SSlmV/Gear21LslYwBEWa8NjacNmIyYzPr7oVitGpofsgkHAKm1KrF6S6udVRsQ97BMINXmqY1YGKX9e3l+EYC8qjZF6OKH/fNTLO7CXkr7Ib8WJulwdZK/zEJSWvG/otqg1Ul6AkAlXWlM1Wv9/Uv1Bk0bc0h9jefU5lGHUJyuESqzbtWrQVCGUP13/Fn9fOGgjzRW2hswKuw+gsjHv04h2ctTFFuW7LN4oWp8xOSin1R8e3qk9YQUCGcYBvuvD+5MGUM9aiCrDAod6mSoS3A/jMu5cPK136L1LSglArOcqFCiQTbUfj6OJPAT1V0FABB09bFLiB8lAbFAagwkv0LvMdwPXyEOAh1A7L2xv0QVqHpJ2oNgWuJwECud7uSPn4gus+Zic//lt3IIS4tlooq2jNyoQ2RdMOmXPXZcjV4KCFTXWddvhX91aOd4I3NBBHPTc/MLEaA9tIKR0zVvk+j1Q1M3S+Jgxp+bhf5XAh2B4oVI5HavRu+nLGpZ+KVT1WrJj/9LauL+hj8TiHqtXIbnS0MuwYSWJ4ZysZiIfvEnF6xs2+90jsLSAd5xGpJgAZDJ5s=
  - secure: Zt0rnYn3//X2wj3JhKOSvonLxDhDGGAkzsCCYvhj0T5tIPn5zohqhZjnc28lntDXKBoNC423kbJKE9oJrXTppuhIvyULPvHfkgPeGEEC9Bmjv6Krx9lkDK+zouMaube+ahsaNxVdrK4A2Z9Y92zWgURuP7C46POuSU8cjx1JKN1diHM/CxDqlK+sQgZbdYho8N+XKSRh6BbmAgP31+qAcG27R92K/o6T07PSxqBhGGOv3hTPlIK/ZNJ5dgx0wOUBddkDzFhcR+MQ1lhRgW7JIBwpoFnsIK6Mtq4yddhp09r2GTvrXN69xtOEHmRR6CxcKD9km19POzigaQCO7xi28MHT04j5xAPTapZVN/vEjnVrVLIHOQC5mFTrP1rjJUmA03iUclf14INyV/PygckKaJByIpLcFMdiXs03knftu2DpmKFcvjpZkXPEKX+ZiDQzsDyauRXHhxakMGo6tOE6a6HAxksgeq4XlamamUBh5EbENA14+z5BYamzzL16+wtrw8TAa8g/nyx0nhcvmAKtXGMMxUzfuNr+CkI/QJNCg9DJA4GP1feyDzfkCCmVNnpL0z/ujMPmwvzgtE1VAoBP9G0CT4TyDiDtwSr0CoOdTNqNVOOb4P2hAFwzytxQmdvq6CcHreFRMAtFTBRt1qS+usVDPaHIfWRKFSlovDVkYQc=
