language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: O3rhY2lmZ34QceUtlG361IDghQH2ZOHltvLUj2qmfc6kWrWmJpM6hixH/h9BeL/LunuhpaRluCSYxMpQAmuDBQcLbm54UNCScVhLwKVBipgqnyXI46pS32CAqiqsSlKMdt2ZrtXJv0cuPxgGSj1LnsM+TqqCPc6tCtREyK2Fg4+FYYaBvlatbxl9rhGeH0vXLPLVRieKa+QvI4S2HVPNatBczhr2+SY1kATiDIfYoO3X+rDf8IapS2tSGJJuWaIBTDkpZ92LFgKFfeGZHT/eoN9RvDlsrUlNZvl0jDxwPO+CRFFWkeZ9hOanIIvW2+Ke9S5NY0ZPjDJ8F0ZdxtPau+/KB5TSuwdcls6EURMNLD+BCRC+aD7/O2TC0Vgu3aqG/IXteRaq6Ba9Uv8A2/8UQrBScc7t9p6xlzcl3kZHXRjzsyd1XsLdM8nSdn6H5gC4V9v5Xn2tQWbKMTnU5nPqiZux2WOimOmxR+FgXORgT+k3hZLlJJvs82Hw7ivJeS+92Dx8Pv28q0oLIvK3/g1oifBX7Q/ZE7Gj+L2GK2xfqTghyuID0EPUxlyNobgKLtJefSZSPSAds9yqVmqGpGP6cuEFRJx6VtcnZ45C/ZiHeJc+40+l4mr98pKsFs/+m7l1B+f+wzirqoxjLj9nh8CE3LeiS+hf1ViHUGxcdcooATg=
  - secure: WZfKlOz2EODpjbSEQV1biBjNBT/ojITFNpkUuQ0HQE9YTlqaksh0M3psNQLCSXb0PKSaSM1TjXKzD1mp1DRjjZbMO+fxQ5zAmF791SgawAWNoHFL+LTF3yvBMUd9dtTY/Fq2JeKqZLnWseNPopTFBwj6yeYSM5bUzcjSK9e9x9sed3cy36cCBl8L96OVIDNAv46xHP+h+jD36fZ1ZwSEGR8lXj631rMR86MSOHQZUlEpm7mELZx3HblDEuWSL+TfCWSqrpDMbzxvXHTO9HDcHpUFnI+CgzqiBpGAjEzLcdOUwd4w3euoF8tZj9If35oejIYymTCkfPLXHs95XAKgiJTUwU6TqGWvIgUEhFw2uxu5sfyIFpxoEC5MVCh1T/Mgyinkzsf07hknxqhHL3d02eKZn5tzjzEzc5U1LQ7+OnAJv/9pfOz3+bZKSYZ5qWWnkijMiwMPM87HEIerkasf25MIL/YUJDtwMS2spu7Z/yeeISZ/1FxheYAI0q++Li3SjSARKvKL4e4DL/1BckkRRZQgvPTE3z9pMZzgESv4d4iWmTuJatkf0tKko3q9hC6BaWMGQvi9p84q7GpJIudPBUBDelRaBEAw0qHZvWMTgjagVcawCs7j6qUcNjp2yKC6aM+sCRDtaEZRU9zkJ1ZRLEXrHVyNHxbSYIkLI00n3bs=
