baseurl = "https://example.org/"
languageCode = "en-us"
title = "Vivekanand Rao's Awesome Collection of Tutorials"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Vivekanand Rao"
    site_description = "The awesome blog of John Doe."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/hugo-logo.png"
    header_background = "img/coffee.jpg"
    header_title = "Awesome Tutorial Collections"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "viveksrao"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "viveksrao"
    gplus     = ""
